apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-status
  namespace: ingress
  labels:
    app: orders-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-status
  template:
    metadata:
      labels:
        app: orders-status
    spec:
      containers:
      - name: orders-status
        image: acrproep01.azurecr.io/orders-status:v1.3
        env:
        - name: TOKEN_ISSUER
          value: urn:prope:identity:issuer
        - name: RESTAURANT_APPLICATION_ORIGIN
          value: https://51.141.4.73
        - name: DRIVERS_APPLICATION_ORIGIN
          value: https://localhost:5002
        ports:
        - containerPort: 3333
          name: socket
        - containerPort: 50051
          name: grpc